definitions:
  models.DefaultError:
    properties:
      errors:
        items:
          type: string
        type: array
    type: object
  models.Recipe:
    properties:
      keywords:
        items:
          type: string
        type: array
      recipes:
        items:
          $ref: '#/definitions/models.Recipes'
        type: array
    type: object
  models.Recipes:
    properties:
      gif:
        type: string
      ingredients:
        items:
          type: string
        type: array
      link:
        type: string
      title:
        type: string
    type: object
info:
  contact: {}
  license: {}
paths:
  /recipes/:
    get:
      description: Gera uma lista de receitas dado ingredientes
      parameters:
      - description: Array de ngredientes (separados por virgula)
        in: query
        name: i
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Recipe'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.DefaultError'
      summary: Index Recipe
      tags:
      - Recipe
swagger: "2.0"
